estimator: XGB
objective: binary:logistic
tree_method: hist
device: cpu
nthread: -1
scale_pos_weight:
  low: 2
  up: 12
n_estimators:
  low: 50
  up: 5000
max_depth:
  low: 5
  up: 30
min_child_weight:
  low: 0
  up: 8
learning_rate:
  low: 0.0001
  up: 0.3
  log: True
subsample:
  low: 0.4
  up: 1.0
  step: 0.01
colsample_bylevel:
  low: 0.2
  up: 1.
  step: 0.1
reg_alpha:
  low: 0
  up: 2
reg_lambda:
  low: 0
  up: 3
gamma:
  low: 0.05
  up: 1.0
