defaults:
    - model: xgb
    - _self_


mode:
  test: true


preprocess:
  raw_path: data/processed/data_v2.csv
  prediction_strategy: binary
  imbalance_strategy: ignore
  baking_strategy: onehot
  X_col:
    - age
    - work_exp
    - is_female_yes
    # - is_lths_yes
    # - is_lths30_yes
    # - is_hsl_yes
    # - is_hsl30_yes
    # - is_teen_yes
    # - edu_college
    # - edu_doctoral
    # - edu_elementary
    # - edu_illiterate
    # - edu_junior_college
    # - edu_junior_high
    # - edu_master
    # - edu_self_study
    # - edu_senior_high_vocational
    # - mar_divorced_separated
    - mar_married_cohabited
    - mar_unmarried
    # - mar_widow_widower
    # - countyname_Changhua_County
    # - countyname_Chiayi_City
    # - countyname_Chiayi_County
    # - countyname_Gaoxiong_City
    # - countyname_Gaoxiong_County
    # - countyname_Hsinchu_City
    # - countyname_Hsinchu_County
    # - countyname_Hualian_County
    # - countyname_Keelung_City
    # - countyname_Miaoli_County
    # - countyname_Nantou_County
    # - countyname_Penghu_County
    # - countyname_Pingtung_County
    # - countyname_Taichung_City
    # - countyname_Taichung_County
    # - countyname_Taidong_County
    # - countyname_Tainan_City
    - countyname_Tainan_County
    # - countyname_Taipei_City
    # - countyname_Taipei_County
    # - countyname_Taoyuan_County
    # - countyname_Yilan_County
    # - countyname_Yunlin_County
  y_col: group1_treatment
  test_size: 0.2
  random_state: 1126
  verbose: True


tune:
  cv: 5
  sampler: TPESampler
  n_trials: 1
